const KEY='portfolio-budget-v1';
const expenseForm=document.querySelector('#expense-form'), list=document.querySelector('#expenses'), filter=document.querySelector('#filter'), limitInput=document.querySelector('#limit');
function load(){try{const d=JSON.parse(localStorage.getItem(KEY)||'{"limit":500,"expenses":[]}');return {limit:Number(d.limit)||500,expenses:Array.isArray(d.expenses)?d.expenses:[]}}catch{return {limit:500,expenses:[]}}}
let state=load(); const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'EUR'}).format(n);
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function render(){const total=state.expenses.reduce((s,e)=>s+e.amount,0),remaining=state.limit-total;document.querySelector('#limit-label').textContent=money(state.limit);document.querySelector('#spent-label').textContent=money(total);document.querySelector('#remaining-label').textContent=money(remaining);const bar=document.querySelector('#progress');bar.max=state.limit;bar.value=Math.min(total,state.limit);document.querySelector('#budget-message').textContent=remaining<0?`Over budget by ${money(-remaining)}.`:`${Math.round(total/state.limit*100)}% of your budget used.`;limitInput.value=state.limit;list.replaceChildren();const shown=state.expenses.filter(e=>filter.value==='all'||e.category===filter.value);if(!shown.length){const li=document.createElement('li');li.textContent='No expenses in this view.';list.append(li)}for(const e of shown){const li=document.createElement('li');const desc=document.createElement('span');desc.textContent=`${e.description} · ${e.category}`;const amount=document.createElement('span');amount.className='amount';amount.textContent=money(e.amount);const del=document.createElement('button');del.type='button';del.className='quiet';del.textContent='Delete';del.setAttribute('aria-label',`Delete ${e.description}`);del.addEventListener('click',()=>{state.expenses=state.expenses.filter(x=>x.id!==e.id);save();render()});li.append(desc,amount,del);list.append(li)}}
document.querySelector('#budget-form').addEventListener('submit',e=>{e.preventDefault();const n=Number(limitInput.value);if(n>0){state.limit=n;save();render()}});
expenseForm.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(expenseForm),description=String(data.get('description')).trim(),amount=Number(data.get('amount'));if(!description||!Number.isFinite(amount)||amount<=0)return;state.expenses.unshift({id:crypto.randomUUID(),description,category:String(data.get('category')),amount});save();expenseForm.reset();render()});
filter.addEventListener('change',render);document.querySelector('#clear').addEventListener('click',()=>{state.expenses=[];save();render()});render();
