const KEY='portfolio-task-board-v1';
const form=document.querySelector('#task-form'), input=document.querySelector('#task-input'), list=document.querySelector('#tasks'), status=document.querySelector('#status');
let tasks=read(), filter='all';
function read(){try{const value=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(value)?value.filter(x=>x&&typeof x.id==='string'&&typeof x.text==='string'):[]}catch{return []}}
function save(){localStorage.setItem(KEY,JSON.stringify(tasks))}
function render(){list.replaceChildren();const shown=tasks.filter(t=>filter==='all'||(filter==='active'&&!t.done)||(filter==='done'&&t.done));status.textContent=shown.length?`${shown.length} task${shown.length===1?'':'s'}`:'No tasks in this view.';for(const task of shown){const li=document.createElement('li');li.className=task.done?'done':'';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=task.done;checkbox.setAttribute('aria-label',`Mark ${task.text} ${task.done?'active':'complete'}`);checkbox.addEventListener('change',()=>{task.done=checkbox.checked;save();render()});const label=document.createElement('label');label.textContent=task.text;const del=document.createElement('button');del.type='button';del.className='delete';del.textContent='Delete';del.setAttribute('aria-label',`Delete ${task.text}`);del.addEventListener('click',()=>{tasks=tasks.filter(t=>t.id!==task.id);save();render()});li.append(checkbox,label,del);list.append(li)}}
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;tasks.unshift({id:crypto.randomUUID(),text,done:false});input.value='';save();render();input.focus()});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()}));
document.querySelector('#clear-done').addEventListener('click',()=>{tasks=tasks.filter(t=>!t.done);save();render()});render();
